language: java
jdk:
  - openjdk8
services:
  - docker

env:
  matrix:
    - COVERAGE=0.5 TARGET=./monolithic/ui

script:
  - ./gradlew clean jar

after_success:
  - ./gradlew -p $TARGET check

before_deploy:
  - ./gradlew -p ./monolithic/ui packageToContainer

deploy:
  provider: script
  script: ./script/deploy.sh
  on:
    condition: "$TARGET == './monolithic/ui'"
    branch: master
