language: java
jdk:
  - openjdk8


env:
  matrix:
    - COVERAGE=0.5 TARGET=./monolithic/ui

script:
  - ./gradlew clean jar

after_success:
  - ./gradlew -p $TARGET check

deploy:
  provider: script
  script: bash -c "echo \"${DOCKER_PASSWORD}\" | docker login --username \"${DOCKER_LOGIN}\" --password-stdin"
  on:
    tags: true
    all_branches: true
